version: '3.4'
services:
  swoft:
    image: swoft/swoft
#    for local develop
#    command: php -S 127.0.0.1:13300
    container_name: library-on-swoft-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    # depends_on:
    #   # - mysql
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./:/var/www/swoft
    command: sh run.sh #运行命令,覆盖了dockerfile的CMD


  # mysql:
  #   image: mysql
  #   container_name: mysql-srv
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #   ports:
  #     - "13306:3306"
  #   volumes:
  #     - ./runtime/data/mysql:/var/lib/mysql
  #   restart: always
