version: '3.4'
services:
  swoft:
    image: swoft/swoft
    container_name: library-on-swoft-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    links:
      - "mysql"
    depends_on:
      - "mysql"
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./:/var/www/swoft
    command: sh swoft-run.sh #运行命令,覆盖了dockerfile的CMD
    networks:
        - book_net

  mysql:
    image: mysql:5.6.46
    container_name: library-on-mysql-srv
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    expose:
      - "3306"
    restart: always
    networks:
      - book_net

networks:
    # 配置docker network
    book_net: