version: '3.4'
services:
  swoft:
    image: swoft/swoft
#    for local develop
#    command: php -S 127.0.0.1:13300
    container_name: library-on-swoft-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    links:
      - "mysql"
    depends_on:
      - "mysql"
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./:/var/www/swoft
    command: sh run.sh #运行命令,覆盖了dockerfile的CMD
    networks:
        - book_net

  mysql:
    image: mysql
    container_name: library-on-mysql-srv
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    expose:
      - "3306"
    volumes:
      - ./runtime/data/mysql:/var/lib/mysql
    restart: always
    networks:
      - book_net
          # # 固定子网ip，网段必须在子网络10.10.*.*
          # ipv4_address: 10.10.10.1

networks:
    # 配置docker network
    book_net: